// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUqhb3iV7WJtD192vlb1HvklRL5OhuWEU',
    appId: '1:731901904437:web:ee4a5a4c6015da56d0d37c',
    messagingSenderId: '731901904437',
    projectId: 'todolist-340ec',
    authDomain: 'todolist-340ec.firebaseapp.com',
    storageBucket: 'todolist-340ec.firebasestorage.app',
    measurementId: 'G-W5E1J7SVL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq7NxseUOyMF8TrIYNwFucBRiM12RZXqk',
    appId: '1:731901904437:android:e3f6a8762a3a3791d0d37c',
    messagingSenderId: '731901904437',
    projectId: 'todolist-340ec',
    storageBucket: 'todolist-340ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCQIpMHI2D9-v2mEv-PGISygRd9VI2Chw',
    appId: '1:731901904437:ios:c046cc66c7e93578d0d37c',
    messagingSenderId: '731901904437',
    projectId: 'todolist-340ec',
    storageBucket: 'todolist-340ec.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUqhb3iV7WJtD192vlb1HvklRL5OhuWEU',
    appId: '1:731901904437:web:395cf8e7a7fe1a0bd0d37c',
    messagingSenderId: '731901904437',
    projectId: 'todolist-340ec',
    authDomain: 'todolist-340ec.firebaseapp.com',
    storageBucket: 'todolist-340ec.firebasestorage.app',
    measurementId: 'G-2D31KLNBR5',
  );
}
